version: '3.7'

# copy and modify this file, and rename to docker-compose.yml to get database running
# don't forget to start docker and enter: sudo docker-compose up

services:
  db:
    image: mysql:latest
    command:
      - "mysqld"
      - "--performance-schema=off"
      - "--key_buffer_size=16M"
      - "--tmp_table_size=1M"
      - "--innodb_buffer_pool_size=1M"
      - "--innodb_log_buffer_size=1M"
      - "--max_connections=25"
      - "--sort_buffer_size=512M"
      - "--read_buffer_size=256K"
      - "--read_rnd_buffer_size=512K"
      - "--join_buffer_size=128K"
      - "--thread_stack=196K"
    volumes:
      - "/media/candra/CODING/database-docker-global/db-data:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: laravel_payment_gateway

volumes:
  db-data:
